# Generated by Django 2.1.3 on 2018-11-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
